baseURL: "https://anirudh-pundir.github.io"
languageCode: "en-us"
title: "Anirudh Pundir"
theme: hugo-profile



markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
  # main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1

    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 2
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Anirudh"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "favicon.ico"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Anirudh"
    subtitle: "I am A developer always craving about developing new projects"
    content: "Logical, organized, highly motivated problem solver. Strong foundation in data structures and algorithms. Experienced in object-oriented
programming, debugging, and testing code.
"
    image: profile.jpeg
    button:
      enable: true
      name: "Resume"
      url: "https://docs.google.com/document/d/1jQLDoqxMOINAbQkl71LRdF_MSxX7zHRjgukfxcqal78/edit#"
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/anirudh-pundir
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/anirudh-pundir/
      

  # About
  about:
    enable: true
    title: "About Me"
    image: profile.jpeg
    content: |-
      I am a  developer with a passion for web development. I have a background in computer science, and I have a strong interest in the intersection of technology and art.  Excellent teamwork,interpersonal and communication skills. Skilled at collaborating with others and also successful in self-directed settings. Experienced in leading projects.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Git"
        - "GitHub"

  # Experience
  experience:
    enable: false
    items:
      - job: "Senior Software Developer"
        company: "Facebook"
        companyUrl: "https://example.com"
        date: "Jan 2022 - present"
        featuredLink:
          enable: true
          name: "View the project"
          url: "https://example.com"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Software Developer"
        company: "Amazon"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Junior Software Developer"
        company: "Apple"
        companyUrl: "https://example.com"
        date: "Jan 2020 - Aug 2020"
        info:
          enable: false
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "UI/UX Designer"
        company: "Netflix"
        companyUrl: "https://example.com"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: true
          url: "https://example.com"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
          - Lead backend developer for a product.
          - Created a frontend design for a product.
      - job: "Product Designer"
        company: "Google"
        companyUrl: "https://example.com"
        date: "Feb 2016 - Mar 2017"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Bachelor of Engineering"
        school:
          name: "Chandigarh University, punjab"
          url: "https://www.cuchd.in/"
        date: "2020 - 2024"
        content: |-
          Extracurricular Activities

            All India University Championship (Volleyball)

            District level Kabbadi Championship (Silver)

      - title: "Intermediate  "
        school:
          name: "Asha Modern School"
          url: "http://ashamodernschool.in/"
        date: "2016 - 2019"
        # content: |
        #   - I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        featuredLink:
          enable: false

         ##title: "High School"
        school:
          name: "Asha Modern School"
          url: "http://ashamodernschool.in/"
          
        
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Portfolio Website
        content: Personal Portfolio static website hosted on GitHub Pages and upgraded regularly using GitHub actions.

        image: portfolio.png
        featured:
          name: Portfolio
          link: https://anirudh-pundir.github.io
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        links:
          - image: portfolio.png
          - icon: fab fa-github
            url: https://github.com/anirudh-pundir
      - title: knowMore
        content: A learning platform to teach programming concepts to students with any level of experience. Learners can learn through interactive learning material which includes quizzes and activities to be solved using a visual programming language
        image: knowMore.jpeg
        featured:
          name: knowMore
          link: https://github.com/anirudh-pundir/learning_platform
        links:
          - icon: fab fa-github
            url: https://github.com/anirudh-pundir

      - title: Musico
        content: A music store page which allows artists to showcase their music which users can play based on their subscriptions.
        image: musico.png
        featured:
          name: Musico
          link: https://github.com/anirudh-pundir/Music-Store-Page
        links:
          - icon: fab fa-github
            url: https://github.com/anirudh-pundir

  #Contact
  contact:
    enable: true
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: pundira907@gmail.com
    btnName: Mail me

  footer:
    socialNetworks:
      github: https://github.com/anirudh-pundir
      linkedin:  https://www.linkedin.com/in/anirudh-pundir/
     # twitter: https://twitter.com
      #instagram: https://instagram.com
     # facebook: https://facebook.com
